/**
 * Ananta Quantum Research Archive & Textbook Library
 * Comprehensive curated corpus of landmark quantum publications,
 * canonical textbooks, and ancient Indian atomic treatises.
 */

const QUANTUM_RESEARCH_PAPERS = [
  // ==========================================
  // 1. FOUNDATIONS & HISTORICAL LANDMARKS
  // ==========================================
  {
    id: 'feynman-1982',
    title: 'Simulating Physics with Computers',
    authors: 'Richard P. Feynman',
    year: 1982,
    venue: 'International Journal of Theoretical Physics, Vol. 21, Nos. 6/7',
    category: 'foundations',
    abstract: 'The legendary paper that birthed the field of quantum computing. Feynman argues that classical computers cannot efficiently simulate quantum mechanical phenomena without an exponential slowdown, proposing instead that computation itself should be built from quantum mechanical elements.',
    doi: '10.1007/BF02650179',
    arxiv: null,
    pdfUrl: 'https://web.eecs.umich.edu/~qstout/pap/Feynman82.pdf',
    circuitPreset: 'superposition',
    bibtex: `@article{feynman1982simulating,
  title={Simulating physics with computers},
  author={Feynman, Richard P},
  journal={International Journal of Theoretical Physics},
  volume={21},
  number={6},
  pages={467--488},
  year={1982},
  publisher={Springer}
}`
  },
  {
    id: 'deutsch-1985',
    title: 'Quantum Theory, the Church-Turing Principle and the Universal Quantum Computer',
    authors: 'David Deutsch',
    year: 1985,
    venue: 'Proceedings of the Royal Society of London. Series A, 400(1818)',
    category: 'foundations',
    abstract: 'Establishes the mathematical foundation for a Universal Quantum Turing Machine. Deutsch proves that quantum computers can perform computational tasks that no classical Turing machine can replicate, introducing the concept of quantum parallelism.',
    doi: '10.1098/rspa.1985.0070',
    arxiv: null,
    pdfUrl: 'https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.1985.0070',
    circuitPreset: 'superposition',
    bibtex: `@article{deutsch1985quantum,
  title={Quantum theory, the Church--Turing principle and the universal quantum computer},
  author={Deutsch, David},
  journal={Proceedings of the Royal Society of London. Series A, Mathematical and Physical Sciences},
  volume={400},
  number={1818},
  pages={97--117},
  year={1985},
  publisher={The Royal Society}
}`
  },
  {
    id: 'epr-1935',
    title: 'Can Quantum-Mechanical Description of Physical Reality be Considered Complete?',
    authors: 'Albert Einstein, Boris Podolsky, Nathan Rosen',
    year: 1935,
    venue: 'Physical Review, 47(10), 777',
    category: 'foundations',
    abstract: 'The historic EPR paradox paper that first identified quantum entanglement. The authors argue that if quantum mechanics is complete, then measurements on spatially separated particles would imply spooky action at a distance, questioning local realism.',
    doi: '10.1103/PhysRev.47.777',
    arxiv: null,
    pdfUrl: 'https://journals.aps.org/pr/pdf/10.1103/PhysRev.47.777',
    circuitPreset: 'bell',
    bibtex: `@article{einstein1935can,
  title={Can quantum-mechanical description of physical reality be considered complete?},
  author={Einstein, Albert and Podolsky, Boris and Rosen, Nathan},
  journal={Physical Review},
  volume={47},
  number={10},
  pages={777},
  year={1935},
  publisher={APS}
}`
  },
  {
    id: 'bell-1964',
    title: 'On the Einstein Podolsky Rosen Paradox',
    authors: 'John Stewart Bell',
    year: 1964,
    venue: 'Physics Physique Fizika, 1(3), 195',
    category: 'foundations',
    abstract: 'Formulates Bell\'s Theorem and Bell\'s Inequalities. Bell mathematically proves that no physical theory based on local hidden variables can reproduce all the statistical predictions of quantum mechanics, paving the way for experimental quantum information.',
    doi: '10.1103/PhysicsPhysiqueFizika.1.195',
    arxiv: null,
    pdfUrl: 'https://cds.cern.ch/record/111475/files/vol1p195-200_001.pdf',
    circuitPreset: 'bell',
    bibtex: `@article{bell1964einstein,
  title={On the Einstein Podolsky Rosen paradox},
  author={Bell, John Stewart},
  journal={Physics Physique Fizika},
  volume={1},
  number={3},
  pages={195},
  year={1964}
}`
  },
  {
    id: 'schumacher-1995',
    title: 'Quantum Coding',
    authors: 'Benjamin Schumacher',
    year: 1995,
    venue: 'Physical Review A, 51(4), 2738',
    category: 'foundations',
    abstract: 'Coins the fundamental term "qubit" and provides the quantum analog to Shannon\'s noiseless coding theorem. Schumacher defines quantum data compression and the density matrix representation for quantum information transmission.',
    doi: '10.1103/PhysRevA.51.2738',
    arxiv: null,
    pdfUrl: 'https://journals.aps.org/pra/pdf/10.1103/PhysRevA.51.2738',
    circuitPreset: null,
    bibtex: `@article{schumacher1995quantum,
  title={Quantum coding},
  author={Schumacher, Benjamin},
  journal={Physical Review A},
  volume={51},
  number={4},
  pages={2738},
  year={1995},
  publisher={APS}
}`
  },

  // ==========================================
  // 2. CANONICAL QUANTUM ALGORITHMS
  // ==========================================
  {
    id: 'shor-1994',
    title: 'Algorithms for Quantum Computation: Discrete Logarithms and Factoring',
    authors: 'Peter W. Shor',
    year: 1994,
    venue: '35th Annual Symposium on Foundations of Computer Science (FOCS)',
    category: 'algorithms',
    abstract: 'Introduces Shor\'s polynomial-time quantum algorithms for prime factorization and discrete logarithms. By leveraging the Quantum Fourier Transform (QFT) to find periods of modular functions, Shor proved quantum computers can break RSA and elliptic curve cryptography in O((log N)^3) time.',
    doi: '10.1109/SFCS.1994.365700',
    arxiv: 'quant-ph/9508027',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/9508027.pdf',
    circuitPreset: null,
    bibtex: `@inproceedings{shor1994algorithms,
  title={Algorithms for quantum computation: discrete logarithms and factoring},
  author={Shor, Peter W},
  booktitle={Proceedings 35th Annual Symposium on Foundations of Computer Science},
  pages={124--134},
  year={1994},
  organization={IEEE}
}`
  },
  {
    id: 'grover-1996',
    title: 'A Fast Quantum Mechanical Algorithm for Database Search',
    authors: 'Lov K. Grover',
    year: 1996,
    venue: '28th Annual ACM Symposium on Theory of Computing (STOC)',
    category: 'algorithms',
    abstract: 'Discovers Grover\'s search algorithm providing a provable quadratic speedup for searching an unstructured database of N items in O(sqrt(N)) queries. Uses iterative amplitude amplification (oracle + diffusion reflection across the mean) to concentrate state probability on the target solution.',
    doi: '10.1145/237814.237866',
    arxiv: 'quant-ph/9605043',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/9605043.pdf',
    circuitPreset: 'grover',
    bibtex: `@inproceedings{grover1996fast,
  title={A fast quantum mechanical algorithm for database search},
  author={Grover, Lov K},
  booktitle={Proceedings of the twenty-eighth annual ACM symposium on Theory of computing},
  pages={212--219},
  year={1996}
}`
  },
  {
    id: 'teleportation-1993',
    title: 'Teleporting an Unknown Quantum State via Dual Classical and Einstein-Podolsky-Rosen Channels',
    authors: 'C. H. Bennett, G. Brassard, C. Crépeau, R. Jozsa, A. Peres, W. K. Wootters',
    year: 1993,
    venue: 'Physical Review Letters, 70(13), 1895',
    category: 'algorithms',
    abstract: 'Discovers quantum teleportation. Demonstrates that an arbitrary unknown qubit can be faithfully disassembled and reconstructed at an arbitrary distance using an entangled Bell state pair and two classical bits of communication, without violating the no-cloning theorem.',
    doi: '10.1103/PhysRevLett.70.1895',
    arxiv: null,
    pdfUrl: 'https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.70.1895',
    circuitPreset: 'teleportation',
    bibtex: `@article{bennett1993teleporting,
  title={Teleporting an unknown quantum state via dual classical and Einstein-Podolsky-Rosen channels},
  author={Bennett, Charles H and Brassard, Gilles and Cr{\'e}peau, Claude and Jozsa, Richard and Peres, Asher and Wootters, William K},
  journal={Physical Review Letters},
  volume={70},
  number={13},
  pages={1895},
  year={1993},
  publisher={APS}
}`
  },
  {
    id: 'hhl-2009',
    title: 'Quantum Algorithm for Linear Systems of Equations',
    authors: 'Aram W. Harrow, Avinatan Hassidim, Seth Lloyd',
    year: 2009,
    venue: 'Physical Review Letters, 103(15), 150502',
    category: 'algorithms',
    abstract: 'Introduces the HHL algorithm for solving sparse linear systems Ax = b exponentially faster than classical Gaussian elimination or conjugate gradient methods. Achieves run time scaling logarithmic in matrix dimension O(log(N) s^2 kappa^2 / epsilon).',
    doi: '10.1103/PhysRevLett.103.150502',
    arxiv: '0811.3171',
    pdfUrl: 'https://arxiv.org/pdf/0811.3171.pdf',
    circuitPreset: null,
    bibtex: `@article{harrow2009quantum,
  title={Quantum algorithm for linear systems of equations},
  author={Harrow, Aram W and Hassidim, Avinatan and Lloyd, Seth},
  journal={Physical Review Letters},
  volume={103},
  number={15},
  pages={150502},
  year={2009},
  publisher={APS}
}`
  },
  {
    id: 'vqe-2014',
    title: 'A Variational Eigenvalue Solver on a Photonic Quantum Processor',
    authors: 'Alberto Peruzzo, Jarrod McClean, Peter Shadbolt, Man-Hong Yung, Xiao-Qi Zhou, Peter J. Love, Alán Aspuru-Guzik, Jeremy L. O\'Brien',
    year: 2014,
    venue: 'Nature Communications, 5, 4213',
    category: 'algorithms',
    abstract: 'Introduces the Variational Quantum Eigensolver (VQE), the flagship hybrid quantum-classical algorithm for the NISQ era. Uses classical optimization of parameterized quantum circuits to find ground state molecular energies, demonstrating chemical precision on He-H+.',
    doi: '10.1038/ncomms5213',
    arxiv: '1304.3061',
    pdfUrl: 'https://arxiv.org/pdf/1304.3061.pdf',
    circuitPreset: null,
    bibtex: `@article{peruzzo2014variational,
  title={A variational eigenvalue solver on a photonic quantum processor},
  author={Peruzzo, Alberto and McClean, Jarrod and Shadbolt, Peter and Yung, Man-Hong and Zhou, Xiao-Qi and Love, Peter J and Aspuru-Guzik, Al{\'a}n and O'Brien, Jeremy L},
  journal={Nature Communications},
  volume={5},
  number={1},
  pages={4213},
  year={2014},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'qaoa-2014',
    title: 'A Quantum Approximate Optimization Algorithm',
    authors: 'Edward Farhi, Jeffrey Goldstone, Sam Gutmann',
    year: 2014,
    venue: 'arXiv:1411.4028',
    category: 'algorithms',
    abstract: 'Introduces QAOA, a shallow-depth quantum algorithm for finding approximate solutions to combinatorial optimization problems (e.g. MaxCut). Alternates between cost and driver Hamiltonian unitaries, optimized through classical feedback.',
    doi: '10.48550/arXiv.1411.4028',
    arxiv: '1411.4028',
    pdfUrl: 'https://arxiv.org/pdf/1411.4028.pdf',
    circuitPreset: null,
    bibtex: `@article{farhi2014quantum,
  title={A quantum approximate optimization algorithm},
  author={Farhi, Edward and Goldstone, Jeffrey and Gutmann, Sam},
  journal={arXiv preprint arXiv:1411.4028},
  year={2014}
}`
  },

  // ==========================================
  // 3. FAULT TOLERANCE & QUANTUM ERROR CORRECTION
  // ==========================================
  {
    id: 'shor-qec-1995',
    title: 'Scheme for Reducing Decoherence in Quantum Computer Memory',
    authors: 'Peter W. Shor',
    year: 1995,
    venue: 'Physical Review A, 52(4), R2493',
    category: 'error-correction',
    abstract: 'The historical breakthrough proving quantum error correction is physically possible despite continuous quantum phase and bit-flip errors. Introduces the 9-qubit Shor code that encodes 1 logical qubit into 9 physical qubits to protect against arbitrary single-qubit errors.',
    doi: '10.1103/PhysRevA.52.R2493',
    arxiv: null,
    pdfUrl: 'https://journals.aps.org/pra/pdf/10.1103/PhysRevA.52.R2493',
    circuitPreset: null,
    bibtex: `@article{shor1995scheme,
  title={Scheme for reducing decoherence in quantum computer memory},
  author={Shor, Peter W},
  journal={Physical Review A},
  volume={52},
  number={4},
  pages={R2493},
  year={1995},
  publisher={APS}
}`
  },
  {
    id: 'steane-1996',
    title: 'Error Correcting Codes in Quantum Theory',
    authors: 'Andrew M. Steane',
    year: 1996,
    venue: 'Physical Review Letters, 77(5), 793',
    category: 'error-correction',
    abstract: 'Introduces the 7-qubit CSS (Calderbank-Shor-Steane) code based on the classical [7,4,3] Hamming code. Demonstrates transversal implementation of single-qubit Clifford gates for fault-tolerant quantum logic.',
    doi: '10.1103/PhysRevLett.77.793',
    arxiv: null,
    pdfUrl: 'https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.77.793',
    circuitPreset: null,
    bibtex: `@article{steane1996error,
  title={Error correcting codes in quantum theory},
  author={Steane, Andrew M},
  journal={Physical Review Letters},
  volume={77},
  number={5},
  pages={793},
  year={1996},
  publisher={APS}
}`
  },
  {
    id: 'kitaev-1997',
    title: 'Fault-Tolerant Quantum Computation by Anyons',
    authors: 'Alexei Yu. Kitaev',
    year: 1997,
    venue: 'Annals of Physics, 303(1), 2-30',
    category: 'error-correction',
    abstract: 'Founds topological quantum error correction and topological quantum computation. Introduces the 2D Toric Code and Surface Code where quantum information is stored in non-local topological degrees of freedom immune to local perturbations.',
    doi: '10.1016/S0003-4916(02)00018-0',
    arxiv: 'quant-ph/9707021',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/9707021.pdf',
    circuitPreset: null,
    bibtex: `@article{kitaev2003fault,
  title={Fault-tolerant quantum computation by anyons},
  author={Kitaev, Alexei Yu},
  journal={Annals of Physics},
  volume={303},
  number={1},
  pages={2--30},
  year={2003},
  publisher={Elsevier}
}`
  },
  {
    id: 'fowler-2012',
    title: 'Surface Codes: Towards Practical Large-Scale Quantum Computation',
    authors: 'Austin G. Fowler, Matteo Mariantoni, John M. Martinis, Andrew N. Cleland',
    year: 2012,
    venue: 'Physical Review A, 86(3), 032324',
    category: 'error-correction',
    abstract: 'The definitive architectural blueprint for modern superconducting quantum computing. Analyzes surface code error correction with a 1% fault-tolerance threshold, nearest-neighbor physical connectivity, and lattice surgery for logical multi-qubit operations.',
    doi: '10.1103/PhysRevA.86.032324',
    arxiv: '1208.0928',
    pdfUrl: 'https://arxiv.org/pdf/1208.0928.pdf',
    circuitPreset: null,
    bibtex: `@article{fowler2012surface,
  title={Surface codes: Towards practical large-scale quantum computation},
  author={Fowler, Austin G and Mariantoni, Matteo and Martinis, John M and Cleland, Andrew N},
  journal={Physical Review A},
  volume={86},
  number={3},
  pages={032324},
  year={2012},
  publisher={APS}
}`
  },

  // ==========================================
  // 4. HARDWARE, NISQ & QUANTUM SUPREMACY
  // ==========================================
  {
    id: 'google-sycamore-2019',
    title: 'Quantum Supremacy Using a Programmable Superconducting Processor',
    authors: 'Frank Arute et al. (Google Quantum AI)',
    year: 2019,
    venue: 'Nature, 574(7779), 505-510',
    category: 'hardware',
    abstract: 'Historic demonstration of quantum computational advantage. Using the 53-qubit Sycamore superconducting processor, Google sampled pseudorandom quantum circuits in 200 seconds, a task calculated to take Summit supercomputer approximately 10,000 years.',
    doi: '10.1038/s41586-019-1666-5',
    arxiv: '1910.11333',
    pdfUrl: 'https://arxiv.org/pdf/1910.11333.pdf',
    circuitPreset: null,
    bibtex: `@article{arute2019quantum,
  title={Quantum supremacy using a programmable superconducting processor},
  author={Arute, Frank and Arya, Kunal and Babbush, Ryan and Bacon, Dave and Bardin, Joseph C and Barends, Rami and Biswas, Rupak and Boixo, Sergio and Brandao, Fernando GSL and Buell, David A and others},
  journal={Nature},
  volume={574},
  number={7779},
  pages={505--510},
  year={2019},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'preskill-nisq-2018',
    title: 'Quantum Computing in the NISQ Era and Beyond',
    authors: 'John Preskill',
    year: 2018,
    venue: 'Quantum, 2, 79',
    category: 'hardware',
    abstract: 'Coins the term NISQ (Noisy Intermediate-Scale Quantum) for processors with 50-1000 physical qubits that lack fault-tolerant error correction. Outlines the scientific prospects for quantum simulation, machine learning, and optimization before full fault tolerance is realized.',
    doi: '10.22331/q-2018-08-06-79',
    arxiv: '1801.00862',
    pdfUrl: 'https://arxiv.org/pdf/1801.00862.pdf',
    circuitPreset: null,
    bibtex: `@article{preskill2018quantum,
  title={Quantum Computing in the {NISQ} era and beyond},
  author={Preskill, John},
  journal={Quantum},
  volume={2},
  pages={79},
  year={2018},
  publisher={Verein zur F{\"o}rderung des Open Access Publizierens in den Quantenwissenschaften}
}`
  },
  {
    id: 'biamonte-qml-2017',
    title: 'Quantum Machine Learning',
    authors: 'Jacob Biamonte, Peter Wittek, Nicola Pancotti, Patrick Rebentrost, Nathan Wiebe, Seth Lloyd',
    year: 2017,
    venue: 'Nature, 549(7671), 195-202',
    category: 'qml',
    abstract: 'Influential Nature review exploring how quantum computers can process high-dimensional vector spaces and solve core linear algebra primitives (PCA, SVM, clustering) exponentially faster than classical machine learning methods.',
    doi: '10.1038/nature23474',
    arxiv: '1611.09347',
    pdfUrl: 'https://arxiv.org/pdf/1611.09347.pdf',
    circuitPreset: null,
    bibtex: `@article{biamonte2017quantum,
  title={Quantum machine learning},
  author={Biamonte, Jacob and Wittek, Peter and Pancotti, Nicola and Rebentrost, Patrick and Wiebe, Nathan and Lloyd, Seth},
  journal={Nature},
  volume={549},
  number={7671},
  pages={195--202},
  year={2017},
  publisher={Nature Publishing Group}
}`
  },

  // ==========================================
  // 5. STANDARD TEXTBOOKS & OPEN CURRICULA
  // ==========================================
  {
    id: 'nielsen-chuang',
    title: 'Quantum Computation and Quantum Information (10th Anniversary Edition)',
    authors: 'Michael A. Nielsen, Isaac L. Chuang',
    year: 2010,
    venue: 'Cambridge University Press',
    category: 'textbooks',
    abstract: 'Affectionately known as "Mike & Ike", this is universally considered the bible of quantum computing. Comprehensive coverage of linear algebra for quantum states, quantum circuits, Shor and Grover algorithms, physical implementations, fault tolerance, and quantum information theory.',
    doi: '10.1017/CBO9780511976667',
    arxiv: null,
    pdfUrl: 'https://www.cambridge.org/highereducation/books/quantum-computation-and-quantum-information/01E10196D0A682A6AEFFEA52D53BE9AE',
    circuitPreset: null,
    bibtex: `@book{nielsen2010quantum,
  title={Quantum computation and quantum information},
  author={Nielsen, Michael A and Chuang, Isaac L},
  year={2010},
  publisher={Cambridge university press}
}`
  },
  {
    id: 'preskill-physics-219',
    title: 'Lecture Notes for Physics 219: Quantum Computation',
    authors: 'John Preskill',
    year: 2023,
    venue: 'California Institute of Technology (Caltech)',
    category: 'textbooks',
    abstract: 'Renowned graduate-level lecture course by theoretical physicist John Preskill at Caltech. In-depth mathematical rigor on density matrices, entanglement measures, quantum channels, stabilizer codes, surface codes, and fault-tolerant architectures.',
    doi: null,
    arxiv: null,
    pdfUrl: 'http://theory.caltech.edu/~preskill/ph219/index.html',
    circuitPreset: null,
    bibtex: `@misc{preskill2023physics219,
  title={Lecture Notes for Physics 219: Quantum Computation},
  author={Preskill, John},
  year={2023},
  publisher={California Institute of Technology}
}`
  },
  {
    id: 'aaronson-democritus',
    title: 'Quantum Computing Since Democritus',
    authors: 'Scott Aaronson',
    year: 2013,
    venue: 'Cambridge University Press',
    category: 'textbooks',
    abstract: 'Brilliant conceptual exploration connecting computational complexity theory, quantum mechanics, the P vs NP problem, time travel, and the nature of physical reality with lucid clarity and wit.',
    doi: '10.1017/CBO9780511979309',
    arxiv: null,
    pdfUrl: 'https://www.scottaaronson.com/democritus/',
    circuitPreset: null,
    bibtex: `@book{aaronson2013quantum,
  title={Quantum computing since Democritus},
  author={Aaronson, Scott},
  year={2013},
  publisher={Cambridge University Press}
}`
  },
  {
    id: 'mermin-textbook',
    title: 'Quantum Computer Science: An Introduction',
    authors: 'N. David Mermin',
    year: 2007,
    venue: 'Cambridge University Press',
    category: 'textbooks',
    abstract: 'Written specifically for computer scientists and programmers with no prior background in physics. Develops quantum computation strictly through linear algebra, Qubits, and quantum logic gates.',
    doi: '10.1017/CBO9780511813870',
    arxiv: null,
    pdfUrl: 'https://www.cambridge.org/highereducation/books/quantum-computer-science/BDC2C57B43997F499252003770D6A7BF',
    circuitPreset: null,
    bibtex: `@book{mermin2007quantum,
  title={Quantum computer science: an introduction},
  author={Mermin, N David},
  year={2007},
  publisher={Cambridge University Press}
}`
  },
  {
    id: 'wong-textbook',
    title: 'Introduction to Classical and Quantum Computing',
    authors: 'Thomas G. Wong',
    year: 2022,
    venue: 'Rooted Grove Publishing (Open Access)',
    category: 'textbooks',
    abstract: 'A modern, accessible, open-access textbook designed for undergraduate and graduate students. Thoroughly covers classical gates, Dirac notation, superposition, quantum circuits, Grover\'s algorithm, and quantum teleportation with hundreds of exercises.',
    doi: null,
    arxiv: '2205.02119',
    pdfUrl: 'https://arxiv.org/pdf/2205.02119.pdf',
    circuitPreset: null,
    bibtex: `@book{wong2022introduction,
  title={Introduction to Classical and Quantum Computing},
  author={Wong, Thomas G},
  year={2022},
  publisher={Rooted Grove}
}`
  },
  {
    id: 'qiskit-textbook',
    title: 'Learn Quantum Computation Using Qiskit',
    authors: 'IBM Quantum Team & Community',
    year: 2024,
    venue: 'IBM Quantum Learning Platform (Interactive Open Access)',
    category: 'textbooks',
    abstract: 'The premier open interactive textbook for hands-on quantum programming. Connects mathematical theory directly to Python Qiskit code examples executable on real IBM Quantum superconducting hardware.',
    doi: null,
    arxiv: null,
    pdfUrl: 'https://learning.quantum.ibm.com/',
    circuitPreset: 'bell',
    bibtex: `@misc{qiskittextbook2024,
  title={Learn Quantum Computation using Qiskit},
  author={{IBM Quantum}},
  year={2024},
  url={https://learning.quantum.ibm.com/}
}`
  },
  {
    id: 'lidar-brun-qec',
    title: 'Quantum Error Correction',
    authors: 'Daniel A. Lidar, Todd A. Brun',
    year: 2013,
    venue: 'Cambridge University Press',
    category: 'textbooks',
    abstract: 'Comprehensive 700-page master reference on quantum fault-tolerance. Covers stabilizer formalism, topological codes, subsystem codes, dynamical decoupling, and error mitigation strategies for physical architectures.',
    doi: '10.1017/CBO9781139034807',
    arxiv: null,
    pdfUrl: 'https://www.cambridge.org/highereducation/books/quantum-error-correction/B44D5514E968F12B26CC7B855CF761A7',
    circuitPreset: null,
    bibtex: `@book{lidar2013quantum,
  title={Quantum error correction},
  author={Lidar, Daniel A and Brun, Todd A},
  year={2013},
  publisher={Cambridge University Press}
}`
  },

  // ==========================================
  // 6. ANCIENT ATOMIC PHILOSOPHY & HERITAGE
  // ==========================================
  {
    id: 'kanada-vaisheshika',
    title: 'Vaisheshika Sutra (The Genesis of Atomic Theory / Parmanu Vada)',
    authors: 'Maharshi Kanada (Aksapada)',
    year: 'c. 600 BCE',
    venue: 'Ancient Indian Philosophical System (Vaisheshika Darshana)',
    category: 'ancient-heritage',
    abstract: 'Authored in the 6th century BCE, this foundational treatise contains the world\'s earliest recorded atomic theory. Kanada states that all matter (Dravya) consists of eternal, indestructible, indivisible spherical particles (Parmanu) in perpetual vibration (Spanda) that combine into dyads (Dvyanuka) and triads (Tryanuka), predicting atomic physics millennia before Dalton.',
    doi: null,
    arxiv: null,
    pdfUrl: 'https://archive.org/details/VaisheshikaSutraOfKanadaWithCommentaryOfSankaraMisra',
    circuitPreset: 'superposition',
    bibtex: `@book{kanada600bce,
  title={Vaisheshika Sutra: A Treatise on Indian Atomism and Physical Categories},
  author={Kanada, Maharshi},
  year={c. 600 BCE},
  note={Translated with commentary by Nandalal Sinha, Sacred Books of the Hindus}
}`
  },
  {
    id: 'prashastapada-bhashya',
    title: 'Padartha Dharma Samgraha (Systematic Analysis of Atomic Motion and Interaction)',
    authors: 'Prashastapada',
    year: 'c. 500 CE',
    venue: 'Classical Sanskrit Physical Commentary',
    category: 'ancient-heritage',
    abstract: 'Extends Kanada\'s atomic framework by formalizing the kinematics of Parmanu, structural bonding through heat energy (Paka), and vibrational resonance (Spandana). Analyzes how discrete quantum units give rise to macroscopic fluid and solid properties.',
    doi: null,
    arxiv: null,
    pdfUrl: 'https://archive.org/details/ThePadarthadharmasamgrahaOfPrasastapadaWithSridharasNyayakandali',
    circuitPreset: null,
    bibtex: `@book{prashastapada500ce,
  title={Padartha Dharma Samgraha: Exposition of Physical Categories},
  author={Prashastapada},
  year={c. 500 CE},
  publisher={Chowkhamba Sanskrit Series}
}`
  },
  {
    id: 'kapila-samkhya',
    title: 'Samkhya Pravachana Sutra (Cosmic Potentiality & The Observer)',
    authors: 'Sage Kapila',
    year: 'c. 700 BCE',
    venue: 'Samkhya Darshana',
    category: 'ancient-heritage',
    abstract: 'Founds the Samkhya system analyzing physical nature (Prakriti) as a continuous multi-dimensional matrix of unmanifest potentiality (Avyakta) held in equilibrium, which collapses into manifest macroscopic states in the presence of the conscious observer (Purusha), foreshadowing wave-particle duality and the measurement problem.',
    doi: null,
    arxiv: null,
    pdfUrl: 'https://archive.org/details/samkhyapravachana00kapiuoft',
    circuitPreset: 'bell',
    bibtex: `@book{kapila700bce,
  title={Samkhya Pravachana Sutra: Philosophy of Nature and the Conscious Observer},
  author={Kapila, Sage},
  year={c. 700 BCE},
  publisher={Sacred Books of the East}
}`
  },

  // ==========================================
  // 7. ADVANCED QUANTUM RESEARCH & FRONTIERS
  // ==========================================
  {
    id: 'aharonov-benor-1997',
    title: 'Fault-Tolerant Quantum Computation with Constant Error',
    authors: 'Dorit Aharonov, Michael Ben-Or',
    year: 1997,
    venue: '29th Annual ACM Symposium on Theory of Computing (STOC)',
    category: 'error-correction',
    abstract: 'Proves the landmark Quantum Threshold Theorem: if the physical error rate per gate is below a constant threshold (η_c > 0), arbitrarily long quantum computations can be executed with arbitrary polynomial accuracy using concatenated quantum codes and polylogarithmic qubit overhead.',
    doi: '10.1145/258533.258579',
    arxiv: 'quant-ph/9611028',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/9611028.pdf',
    circuitPreset: null,
    bibtex: `@inproceedings{aharonov1997fault,
  title={Fault-tolerant quantum computation with constant error},
  author={Aharonov, Dorit and Ben-Or, Michael},
  booktitle={Proceedings of the twenty-ninth annual ACM symposium on Theory of computing},
  pages={176--188},
  year={1997}
}`
  },
  {
    id: 'google-surface-code-2023',
    title: 'Suppressing Quantum Errors by Scaling a Quantum Error-Correcting Code',
    authors: 'Google Quantum AI (Rajeev Acharya et al.)',
    year: 2023,
    venue: 'Nature, 614(7949), 676-681',
    category: 'error-correction',
    abstract: 'Milestone experimental demonstration showing for the first time that scaling a surface code from distance-3 (17 qubits) to distance-5 (49 qubits) suppresses the logical error rate per cycle from 3.028% to 2.914%, confirming that physical superconducting transmons operate below the fault-tolerance threshold.',
    doi: '10.1038/s41586-022-05434-1',
    arxiv: '2207.06431',
    pdfUrl: 'https://arxiv.org/pdf/2207.06431.pdf',
    circuitPreset: null,
    bibtex: `@article{google2023suppressing,
  title={Suppressing quantum errors by scaling a quantum error-correcting code},
  author={{Google Quantum AI}},
  journal={Nature},
  volume={614},
  number={7949},
  pages={676--681},
  year={2023},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'bluvstein-harvard-2023',
    title: 'A Quantum Processor Based on Coherent Transport of Neutral Atoms',
    authors: 'Dolev Bluvstein, Simon J. Evered, Alexandra A. Geim, Sophie H. Li, Hengyun Zhou et al. (Harvard / MIT / QuEra)',
    year: 2023,
    venue: 'Nature, 626(7997), 58-65',
    category: 'hardware',
    abstract: 'Breakthrough demonstration of dynamic neutral atom arrays with 48 dual-rail logical qubits, arbitrary connectivity via optical tweezer shuttling, fault-tolerant logical entangling gates, and transversal non-Clifford operations, establishing neutral atoms as a premier fault-tolerant computing architecture.',
    doi: '10.1038/s41586-023-06927-3',
    arxiv: '2312.03818',
    pdfUrl: 'https://arxiv.org/pdf/2312.03818.pdf',
    circuitPreset: null,
    bibtex: `@article{bluvstein2023quantum,
  title={A quantum processor based on coherent transport of neutral atoms},
  author={Bluvstein, Dolev and Evered, Simon J and Geim, Alexandra A and Li, Sophie H and Zhou, Hengyun and others},
  journal={Nature},
  volume={626},
  number={7997},
  pages={58--65},
  year={2023},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'gidney-ekera-2021',
    title: 'How to Factor 2048 Bit RSA Integers in 8 Hours Using 20 Million Noisy Qubits',
    authors: 'Craig Gidney, Martin Ekerå',
    year: 2021,
    venue: 'Quantum, 5, 433',
    category: 'algorithms',
    abstract: 'The definitive modern resource estimation for Shor\'s algorithm on fault-tolerant surface codes. Reduces the physical qubit requirement to factor RSA-2048 by two orders of magnitude (from ~1 billion to 20 million physical qubits) by introducing carry-save adders and windowed modular exponentiation.',
    doi: '10.22331/q-2021-04-15-433',
    arxiv: '1905.09749',
    pdfUrl: 'https://arxiv.org/pdf/1905.09749.pdf',
    circuitPreset: null,
    bibtex: `@article{gidney2021factor,
  title={How to factor 2048 bit RSA integers in 8 hours using 20 million noisy qubits},
  author={Gidney, Craig and Eker{\aa}, Martin},
  journal={Quantum},
  volume={5},
  pages={433},
  year={2021},
  publisher={Verein zur F{\"o}rderung des Open Access Publizierens in den Quantenwissenschaften}
}`
  },
  {
    id: 'lloyd-1996',
    title: 'Universal Quantum Simulators',
    authors: 'Seth Lloyd',
    year: 1996,
    venue: 'Science, 273(5278), 1073-1078',
    category: 'algorithms',
    abstract: 'Proves Richard Feynman\'s 1982 conjecture that a universal quantum computer can efficiently simulate any local quantum system. Uses Suzuki-Trotter product formulas to construct explicit polynomial-time quantum circuits for time evolution under arbitrary local Hamiltonians.',
    doi: '10.1126/science.273.5278.1073',
    arxiv: null,
    pdfUrl: 'https://www.science.org/doi/10.1126/science.273.5278.1073',
    circuitPreset: null,
    bibtex: `@article{lloyd1996universal,
  title={Universal quantum simulators},
  author={Lloyd, Seth},
  journal={Science},
  volume={273},
  number={5278},
  pages={1073--1078},
  year={1996},
  publisher={American Association for the Advancement of Science}
}`
  },
  {
    id: 'cerezo-vqa-2021',
    title: 'Variational Quantum Algorithms',
    authors: 'M. Cerezo, Andrew Arrasmith, Ryan Babbush, Simon C. Benjamin, Suguru Endo, Keisuke Fujii, Jarrod R. McClean, Kosuke Mitarai, Xiao Yuan, Lukasz Cincio, Patrick J. Coles',
    year: 2021,
    venue: 'Nature Reviews Physics, 3(9), 625-644',
    category: 'qml',
    abstract: 'The definitive review on Variational Quantum Algorithms (VQAs) across chemistry, optimization, linear algebra, and machine learning. Systematically addresses trainability barriers including barren plateaus, cost function locality, gradient estimation via the parameter-shift rule, and quantum error mitigation.',
    doi: '10.1038/s42254-021-00348-9',
    arxiv: '2012.09265',
    pdfUrl: 'https://arxiv.org/pdf/2012.09265.pdf',
    circuitPreset: 'vqe',
    bibtex: `@article{cerezo2021variational,
  title={Variational quantum algorithms},
  author={Cerezo, Marco and Arrasmith, Andrew and Babbush, Ryan and Benjamin, Simon C and Endo, Suguru and Fujii, Keisuke and McClean, Jarrod R and Mitarai, Kosuke and Yuan, Xiao and Cincio, Lukasz and others},
  journal={Nature Reviews Physics},
  volume={3},
  number={9},
  pages={625--644},
  year={2021},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'gisin-qkd-2002',
    title: 'Quantum Cryptography',
    authors: 'Nicolas Gisin, Grégoire Ribordy, Wolfgang Tittel, Hugo Zbinden',
    year: 2002,
    venue: 'Reviews of Modern Physics, 74(1), 145-195',
    category: 'cryptography',
    abstract: 'Canonical 50-page review of theoretical and experimental quantum cryptography. Covers single-photon and entangled-state QKD protocols (BB84, E91, B92), photon statistics, eavesdropping strategies, quantum repeaters, and practical security proofs in optical fiber telecommunications.',
    doi: '10.1103/RevModPhys.74.145',
    arxiv: 'quant-ph/0101098',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/0101098.pdf',
    circuitPreset: null,
    bibtex: `@article{gisin2002quantum,
  title={Quantum cryptography},
  author={Gisin, Nicolas and Ribordy, Gr{\'e}goire and Tittel, Wolfgang and Zbinden, Hugo},
  journal={Reviews of Modern Physics},
  volume={74},
  number={1},
  pages={145},
  year={2002},
  publisher={APS}
}`
  },
  {
    id: 'childs-walk-2010',
    title: 'Universal Computation by Quantum Walk',
    authors: 'Andrew M. Childs',
    year: 2009,
    venue: 'Physical Review Letters, 102(18), 180501',
    category: 'algorithms',
    abstract: 'Proves that single-particle continuous-time quantum walks on unweighted graphs are computationally universal for quantum computation. Demonstrates that any circuit-model computation can be translated directly into the spatial propagation of a single quantum walker across graph vertices.',
    doi: '10.1103/PhysRevLett.102.180501',
    arxiv: '0806.1972',
    pdfUrl: 'https://arxiv.org/pdf/0806.1972.pdf',
    circuitPreset: null,
    bibtex: `@article{childs2009universal,
  title={Universal computation by quantum walk},
  author={Childs, Andrew M},
  journal={Physical Review Letters},
  volume={102},
  number={18},
  pages={180501},
  year={2009},
  publisher={APS}
}`
  },
  {
    id: 'kitaev-textbook-2002',
    title: 'Classical and Quantum Computation',
    authors: 'A. Yu. Kitaev, A. H. Shen, M. N. Vyalyi',
    year: 2002,
    venue: 'Graduate Studies in Mathematics, Vol. 47, American Mathematical Society',
    category: 'textbooks',
    abstract: 'Masterful graduate-level mathematical foundation connecting classical complexity theory (P, NP, Cook-Levin) with quantum complexity (BQP, QMA, Kitaev\'s Local Hamiltonian theorem), Phase Estimation, and Anyonic topological quantum memory.',
    doi: '10.1090/gsm/047',
    arxiv: null,
    pdfUrl: 'https://bookstore.ams.org/gsm-47',
    circuitPreset: null,
    bibtex: `@book{kitaev2002classical,
  title={Classical and quantum computation},
  author={Kitaev, Alexei Yu and Shen, Alexander and Vyalyi, Mikhail N},
  volume={47},
  year={2002},
  publisher={American Mathematical Society}
}`
  },
  {
    id: 'preskill-advantage-2023',
    title: 'Quantum Advantage and Noise',
    authors: 'John Preskill',
    year: 2023,
    venue: 'arXiv:2308.06450 / Caltech Quantum Science Institute',
    category: 'hardware',
    abstract: 'Authoritative analysis on the physical and algorithmic boundary of quantum computational advantage in the presence of noise. Explores how tensor network classical simulations challenge random circuit sampling, and outlines the verifiable pathways to practical, noise-resilient quantum advantage.',
    doi: '10.48550/arXiv.2308.06450',
    arxiv: '2308.06450',
    pdfUrl: 'https://arxiv.org/pdf/2308.06450.pdf',
    circuitPreset: null,
    bibtex: `@article{preskill2023quantum,
  title={Quantum advantage and noise},
  author={Preskill, John},
  journal={arXiv preprint arXiv:2308.06450},
  year={2023}
}`
  },
  // ==========================================
  // NEW LANDMARK PAPERS
  // ==========================================
  {
    id: 'arute-2019-supremacy',
    title: 'Quantum Supremacy Using a Programmable Superconducting Processor',
    authors: 'Frank Arute, Kunal Arya, Ryan Babbush, Dave Bacon, Joseph C. Bardin, Rami Barends, Rupak Biswas, Sergio Boixo ... (Google AI Quantum)',
    year: 2019,
    venue: 'Nature, 574, 505-510',
    category: 'hardware',
    abstract: 'Google\'s landmark paper demonstrating quantum computational supremacy: Sycamore (53 qubits) completed a random circuit sampling task in 200 seconds that would require ~10,000 years on Summit, the world\'s most powerful classical supercomputer at the time. This is the first experimental demonstration that quantum hardware can surpass classical simulation for a well-defined computational task.',
    doi: '10.1038/s41586-019-1666-5',
    arxiv: '1910.11333',
    pdfUrl: 'https://arxiv.org/pdf/1910.11333.pdf',
    circuitPreset: null,
    bibtex: `@article{arute2019quantum,
  title={Quantum supremacy using a programmable superconducting processor},
  author={Arute, Frank and others},
  journal={Nature},
  volume={574},
  pages={505--510},
  year={2019},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'zhong-2020-photonic',
    title: 'Quantum Computational Advantage Using Photons',
    authors: 'Han-Sen Zhong, Hui Wang, Yu-Hao Deng, Ming-Cheng Chen, Li-Chao Peng, Yi-Han Luo ... (Jian-Wei Pan, USTC)',
    year: 2020,
    venue: 'Science, 370(6523), 1460-1463',
    category: 'hardware',
    abstract: 'The USTC team demonstrated Gaussian Boson Sampling quantum computational advantage using 76 photons on a 100-mode optical interferometer (Jiuzhang). The device performed sampling 10^14 times faster than state-of-the-art classical simulations, establishing a second platform (photonics) achieving quantum advantage beyond Google\'s superconducting demonstration.',
    doi: '10.1126/science.abe8770',
    arxiv: '2012.01625',
    pdfUrl: 'https://arxiv.org/pdf/2012.01625.pdf',
    circuitPreset: null,
    bibtex: `@article{zhong2020quantum,
  title={Quantum computational advantage using photons},
  author={Zhong, Han-Sen and others},
  journal={Science},
  volume={370},
  number={6523},
  pages={1460--1463},
  year={2020},
  publisher={AAAS}
}`
  },
  {
    id: 'kitaev-2003-topological',
    title: 'Fault-Tolerant Quantum Computation by Anyons',
    authors: 'Alexei Kitaev',
    year: 2003,
    venue: 'Annals of Physics, 303(1), 2-30',
    category: 'error_correction',
    abstract: 'Kitaev introduces the toric code — a 2D topological quantum error correcting code whose ground state degeneracy is topological and protected against local perturbations. The paper establishes the theoretical foundation for topological quantum computation and the surface code, which is now the leading architecture for fault-tolerant quantum computers.',
    doi: '10.1016/S0003-4916(02)00018-0',
    arxiv: 'quant-ph/9707021',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/9707021.pdf',
    circuitPreset: null,
    bibtex: `@article{kitaev2003fault,
  title={Fault-tolerant quantum computation by anyons},
  author={Kitaev, Alexei Yu},
  journal={Annals of Physics},
  volume={303},
  number={1},
  pages={2--30},
  year={2003},
  publisher={Elsevier}
}`
  },
  {
    id: 'fowler-2012-surface',
    title: 'Surface Codes: Towards Practical Large-Scale Quantum Computation',
    authors: 'Austin G. Fowler, Matteo Martinis, John M. Martinis, Andrew N. Cleland',
    year: 2012,
    venue: 'Physical Review A, 86(3), 032324',
    category: 'error_correction',
    abstract: 'The definitive practical reference on surface codes, providing rigorous threshold analysis (~1%), circuit-level noise modeling, logical gate implementations, and resource estimation for fault-tolerant quantum computing. This paper is the primary guide used by IBM, Google, and Microsoft for their fault-tolerant hardware roadmaps.',
    doi: '10.1103/PhysRevA.86.032324',
    arxiv: '1208.0928',
    pdfUrl: 'https://arxiv.org/pdf/1208.0928.pdf',
    circuitPreset: null,
    bibtex: `@article{fowler2012surface,
  title={Surface codes: Towards practical large-scale quantum computation},
  author={Fowler, Austin G and Martinis, John M and Cleland, Andrew N},
  journal={Physical Review A},
  volume={86},
  number={3},
  pages={032324},
  year={2012},
  publisher={APS}
}`
  },
  {
    id: 'preskill-2018-nisq',
    title: 'Quantum Computing in the NISQ Era and Beyond',
    authors: 'John Preskill',
    year: 2018,
    venue: 'Quantum, 2, 79',
    category: 'hardware',
    abstract: 'Preskill coins the term "NISQ" (Noisy Intermediate-Scale Quantum) to describe the 50-1000 qubit quantum devices of the near term. He analyzes what quantum advantages might be achievable with NISQ devices, discusses variational algorithms (VQE, QAOA), quantum simulation, and the long road to fault-tolerant universal quantum computing. A landmark framing paper for the entire field.',
    doi: '10.22331/q-2018-08-06-79',
    arxiv: '1801.00862',
    pdfUrl: 'https://arxiv.org/pdf/1801.00862.pdf',
    circuitPreset: null,
    bibtex: `@article{preskill2018quantum,
  title={Quantum computing in the {NISQ} era and beyond},
  author={Preskill, John},
  journal={Quantum},
  volume={2},
  pages={79},
  year={2018},
  publisher={Verein zur F{\"o}rderung des Open Access Publizierens in den Quantenwissenschaften}
}`
  },
  {
    id: 'peruzzo-2014-vqe',
    title: 'A Variational Eigenvalue Solver on a Photonic Chip',
    authors: 'Alberto Peruzzo, Jarrod McClean, Peter Shadbolt, Man-Hong Yung, Xiao-Qi Zhou, Peter J. Love, Alán Aspuru-Guzik, Jeremy L. O\'Brien',
    year: 2014,
    venue: 'Nature Communications, 5, 4213',
    category: 'algorithms',
    abstract: 'The original VQE paper: Peruzzo et al. demonstrate the first variational quantum eigensolver on a photonic chip, computing the energy of the hydrogen molecule (HeH+) using a hybrid quantum-classical feedback loop. This paper launched the entire field of variational quantum algorithms (VQE, QAOA, QNN) and is one of the most cited quantum computing papers.',
    doi: '10.1038/ncomms5213',
    arxiv: '1304.3061',
    pdfUrl: 'https://arxiv.org/pdf/1304.3061.pdf',
    circuitPreset: null,
    bibtex: `@article{peruzzo2014variational,
  title={A variational eigenvalue solver on a photonic chip},
  author={Peruzzo, Alberto and others},
  journal={Nature Communications},
  volume={5},
  pages={4213},
  year={2014},
  publisher={Nature Publishing Group}
}`
  },
  {
    id: 'farhi-2014-qaoa',
    title: 'A Quantum Approximate Optimization Algorithm',
    authors: 'Edward Farhi, Jeffrey Goldstone, Sam Gutmann',
    year: 2014,
    venue: 'arXiv:1411.4028 [quant-ph]',
    category: 'algorithms',
    abstract: 'The original QAOA paper. Farhi, Goldstone, and Gutmann introduce the Quantum Approximate Optimization Algorithm for combinatorial optimization problems. The paper proves QAOA with p=1 layers achieves an approximation ratio of 0.6924 for MAX-CUT on 3-regular graphs, and conjectures that deeper circuits approach the optimal solution. QAOA is now one of the most studied near-term quantum algorithms.',
    doi: '10.48550/arXiv.1411.4028',
    arxiv: '1411.4028',
    pdfUrl: 'https://arxiv.org/pdf/1411.4028.pdf',
    circuitPreset: null,
    bibtex: `@article{farhi2014quantum,
  title={A quantum approximate optimization algorithm},
  author={Farhi, Edward and Goldstone, Jeffrey and Gutmann, Sam},
  journal={arXiv preprint arXiv:1411.4028},
  year={2014}
}`
  },
  {
    id: 'cerezo-2021-barren',
    title: 'Cost-Function-Dependent Barren Plateaus in Shallow Quantum Neural Networks',
    authors: 'Marco Cerezo, Akira Sone, Tyler Volkoff, Lukasz Cincio, Patrick J. Coles',
    year: 2021,
    venue: 'Nature Communications, 12, 1791',
    category: 'algorithms',
    abstract: 'Cerezo et al. prove that global cost functions (acting on all qubits) exhibit barren plateaus for any circuit depth, while local cost functions (measuring only a subset of qubits) avoid barren plateaus for shallow circuits. This provides concrete guidelines for trainable variational circuit design and is the key reference for VQC trainability.',
    doi: '10.1038/s41467-021-21728-w',
    arxiv: '2001.00550',
    pdfUrl: 'https://arxiv.org/pdf/2001.00550.pdf',
    circuitPreset: null,
    bibtex: `@article{cerezo2021cost,
  title={Cost function dependent barren plateaus in shallow parametrized quantum circuits},
  author={Cerezo, Marco and others},
  journal={Nature Communications},
  volume={12},
  pages={1791},
  year={2021}
}`
  },
  {
    id: 'bravyi-2005-magic',
    title: 'Universal Quantum Computation with Ideal Clifford Gates and Noisy Ancillas',
    authors: 'Sergei Bravyi, Alexei Kitaev',
    year: 2005,
    venue: 'Physical Review A, 71(2), 022316',
    category: 'error_correction',
    abstract: 'The original magic state distillation paper. Bravyi and Kitaev prove that Clifford gates plus the ability to prepare noisy magic states |T⟩ is sufficient for universal quantum computation. They introduce the 15-to-1 distillation protocol that purifies noisy T states into high-fidelity ones. This is the standard approach for achieving universal fault-tolerant computation beyond Clifford circuits.',
    doi: '10.1103/PhysRevA.71.022316',
    arxiv: 'quant-ph/0403025',
    pdfUrl: 'https://arxiv.org/pdf/quant-ph/0403025.pdf',
    circuitPreset: null,
    bibtex: `@article{bravyi2005universal,
  title={Universal quantum computation with ideal Clifford gates and noisy ancillas},
  author={Bravyi, Sergei and Kitaev, Alexei},
  journal={Physical Review A},
  volume={71},
  number={2},
  pages={022316},
  year={2005},
  publisher={APS}
}`
  },
  {
    id: 'cross-2019-quantum-volume',
    title: 'Validating Quantum Computers Using Randomized Model Circuits',
    authors: 'Andrew W. Cross, Lev S. Bishop, Sarah Sheldon, Paul D. Nation, Jay M. Gambetta',
    year: 2019,
    venue: 'Physical Review A, 100(3), 032328',
    category: 'hardware',
    abstract: 'IBM introduces Quantum Volume (QV) — a single-number metric that holistically benchmarks quantum processor performance accounting for qubit number, connectivity, gate fidelity, and measurement errors. A QV-N processor can successfully execute random model circuits of depth N on N qubits. QV has become a standard industry benchmark alongside T1, T2, and CNOT fidelity.',
    doi: '10.1103/PhysRevA.100.032328',
    arxiv: '1811.12926',
    pdfUrl: 'https://arxiv.org/pdf/1811.12926.pdf',
    circuitPreset: null,
    bibtex: `@article{cross2019validating,
  title={Validating quantum computers using randomized model circuits},
  author={Cross, Andrew W and others},
  journal={Physical Review A},
  volume={100},
  number={3},
  pages={032328},
  year={2019},
  publisher={APS}
}`
  },
  {
    id: 'bennett-1984-bb84',
    title: 'Quantum Cryptography: Public Key Distribution and Coin Tossing',
    authors: 'Charles H. Bennett, Gilles Brassard',
    year: 1984,
    venue: 'Proceedings of IEEE International Conference on Computers, Systems and Signal Processing, Bangalore, India',
    category: 'cryptography',
    abstract: 'The landmark paper introducing BB84 — the world\'s first quantum key distribution protocol. Bennett and Brassard show how quantum mechanics guarantees secure key distribution: any eavesdropping is detectable, making the keys information-theoretically secure. BB84 launched the field of quantum cryptography and is the basis for all commercial QKD systems.',
    doi: null,
    arxiv: null,
    pdfUrl: 'https://researcher.watson.ibm.com/researcher/files/us-bennetc/BB84highest.pdf',
    circuitPreset: null,
    bibtex: `@inproceedings{bennett1984quantum,
  title={Quantum cryptography: Public key distribution and coin tossing},
  author={Bennett, Charles H and Brassard, Gilles},
  booktitle={Proceedings of IEEE International Conference on Computers, Systems and Signal Processing},
  pages={175--179},
  year={1984}
}`
  },
  {
    id: 'harrow-2009-hhl',
    title: 'Quantum Algorithm for Linear Systems of Equations',
    authors: 'Aram W. Harrow, Avinatan Hassidim, Seth Lloyd',
    year: 2009,
    venue: 'Physical Review Letters, 103(15), 150502',
    category: 'algorithms',
    abstract: 'The HHL algorithm provides an exponential speedup for solving N-dimensional linear systems Ax=b, running in O(log N · poly(κ, 1/ε)) time vs classical O(N·κ). HHL launched the fields of quantum machine learning and quantum linear algebra, enabling quantum speedups in finance, logistics, and fluid simulation. (Note: dequantization results (Tang 2018) showed that classical algorithms can match HHL in many cases, motivating refined quantum advantage analysis.)',
    doi: '10.1103/PhysRevLett.103.150502',
    arxiv: '0811.3171',
    pdfUrl: 'https://arxiv.org/pdf/0811.3171.pdf',
    circuitPreset: null,
    bibtex: `@article{harrow2009quantum,
  title={Quantum algorithm for linear systems of equations},
  author={Harrow, Aram W and Hassidim, Avinatan and Lloyd, Seth},
  journal={Physical Review Letters},
  volume={103},
  number={15},
  pages={150502},
  year={2009},
  publisher={APS}
}`
  }
];

if (typeof window !== 'undefined') {
  window.QUANTUM_RESEARCH_PAPERS = QUANTUM_RESEARCH_PAPERS;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { QUANTUM_RESEARCH_PAPERS };
}

